on:
  workflow_dispatch:
  

jobs:
  release:
    name: Release empty module
    
    runs-on:
    - ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set to Alpha branch
      shell: bash
      run: |
        sed -i "s/mihomo_tag=.*/mihomo_tag=\"Prerelease-Alpha\"/" ./files.config
    
    - name: Build arm64
      shell: bash
      run: |
        sed -i "s/pack_arch=.*/pack_arch=\"arm64\"/" ./files.config
        bash ./pack.sh -c
  
    - name: Build amd64
      shell: bash
      run: |
        sed -i "s/pack_arch=.*/pack_arch=\"amd64\"/" ./files.config
        bash ./pack.sh -c
  
    - name: Save Artifacts ARM64
      uses: actions/upload-artifact@v4
      with:
        name: release-alpha-arm64
        path: release-arm64
  
    - name: Save Artifacts AMD64
      uses: actions/upload-artifact@v4
      with:
        name: release-alpha-amd64
        path: release-amd64
  
    - name: Save Version
      uses: actions/upload-artifact@v4
      with:
        name: version.txt
        path: version
  